#
#Tue Jan 27 17:16:39 EET 2026
sqlbrowserfx.css.theme=flat-dark
sqlbrowserfx.default.editmode.cell=false
sqlbrowserfx.mode=advanced
sqlbrowserfx.root.path=/home/paris/angular-workspace
sqlconnector.enable.autocommit=true
