#
#Tue Mar 10 13:34:47 EET 2026
sqlbrowserfx.css.theme=tokyo-night
sqlbrowserfx.default.editmode.cell=false
sqlbrowserfx.mode=advanced
sqlbrowserfx.root.path=/home/
sqlconnector.enable.autocommit=true
