#
#Tue Mar 10 13:34:47 EET 2026
# tokyo-night, flat-dark, dracula, flat-light
sqlbrowserfx.css.theme=flat-dark
sqlbrowserfx.default.editmode.cell=false
sqlbrowserfx.mode=advanced
sqlbrowserfx.root.path=/home/
sqlbrowserfx.store.passwords=true
sqlconnector.enable.autocommit=true

ollama.url=http://192.168.2.4:11434
ollama.model=qwen2.5-coder:7b